language: python

install:
- pip install tox

script: tox

jobs:
  include:
  - python: '3.6'
    env: TOXENV=py36
  - python: '3.7'
    env: TOXENV=py37
  - python: '3.8'
    env: TOXENV=py38
  - python: '3.6'
    env: TOXENV=flake8
  - stage: deploy
    script: echo "Deploying on PyPi ..."
    env:
    install:
    deploy:
      provider: pypi
      user: JosefFriedrich
      password:
        secure: "SCcC+JzoJRrCR44wekJYIwqw3hJ+m9/EH68dyF3uwb6tErMQ9/hVkNnlc2sdQUsaOV4gr01OcMOO1AKfdlecIZVVw7GNxy3c4uyMSK720gNaGZok2Te46TGrT4EN7TPwZhcMI4aEdrnmw+18uhuyf7CACphcUTv2c3EimrKm57caNQJbPqs7wEk19fGNu+QLHkW+EGTy65px07Kr+a++1SpT1tr2gMjI5OJKzxuUA7afidFpwxtjon30MDSR1+bUUiuiAY26eJxGN41Qfak8N4QOgUEqKXXLOz1eZ4qQSy2gBFKKVZjkEGm0/D2hT85Wrq3IR/7l9XeCVrGXc7RKIK+R41m/xjkxwABDqYLu23ReAi51LNjUnuJL2LV5mQ0BLtBI5LJRhXrrejEXuoo6DV9x14YML65Xv8Z7btkRtVX7XAV3j8eIAegSe5jEuh0bIKPWNZU8zjC+xmflefJeUC7yEJ8XGv3MkK3cwCLCclu+XJP4hrfUinWeGFTADrwu4voB+CZhzcnp+3swyJRdVa6B8oeqWi/6FDaRMU3PNqNlpiaU5MvCg0FNossBw5a1xBLSqC++I6E+NiLC2W0Cw68YYAaDQCFapgfX1+OH9/xqKsMpJI2HdncGHTVlHgkjavd+91QOSyR5PiuxLx01gJS3Nha/sXvoq2l+0tCSEH0="
      on:
        tags: true
